redisdedup: add bitmap
od2/hive pull request #5
Opened 2020-12-09 23:11 UTC by terorie

Solves #3

2020-12-10 16:53 UTC, fionera requested changes

2020-12-10 16:58 UTC, terorie commented on pkg/redisdedup/bitmap.go
> +		if err == nil {
@fionera That was supposed to be deliberate. Good point though, so the items won't get returned when iterating. I didn't intend `redisdedup` to be a storage mechanism though and use it as a pure deduplicator without Iter() support. We should clarify the tasks it will take on.

The Dedup is designed to say either "I have seen this item for sure", or say "maybe not", so basically the opposite of a bloom filter.

When you insert a non-number, and then ask the Dedup whether that number was already seen, it will always say no. I imagine this is useful for collections where 99% are incrementing IDs and 3 annoying keys are strings.

But I don't mind either way, I see 3 options:
- Keep it as it is, and use MySQL for persistence.
- Error out trying to insert non-numeric items.
- Give dedup a Redis SET backing store for keys that are not compatible with bitmap.

2020-12-11 16:04 UTC, terorie commented on pkg/redisdedup/bitmap.go
> +		if err == nil {
As discussed in Keybase, error-ing out on non-numeric items is a better behavior than what the code does currently. I'll try to add that today!

2020-12-12 18:51 UTC, terorie commented on pkg/redisdedup/bitmap.go
> +		if err == nil {
Adjusted to error out

2020-12-12 18:54 UTC, fionera approved these changes

2020-12-12 18:54 UTC, merged